# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [[redirects]]
#   from = "/api/*"
#   to = "https://nftlooker.herokuapp.com/api/:splat"
#   status = 200

#[[headers]]
#  for = "/*"
#    [headers.values]
#    Access-Control-Allow-Origin = "*"